### ISSUE TITLE
Cannot run Elizabeth for setting more than 7 days

### ISSUE THREAD

**Issue by blueneogeo** [pwaldhauer/elizabeth#26]
I made sure I pulled the latest version... I get this error (default set to 150 in elizabeth config to test):

ellie.js export --output DayOneExport --directory /Users/christianvogel/Dropbox\ \(Personal\)/Apps/Day\ One/Journal.dayone
Welcome to Elizabeth, your Moves.app exporter!
----------------------------------------------

> Using DayOneExport to export 150 days!

/usr/local/lib/node_modules/elizabeth/lib/output/DayOneExport.js:56
    if(day.segments == null) return;
          ^
TypeError: Cannot read property 'segments' of undefined
    at DefaultPlugin.exportDay (/usr/local/lib/node_modules/elizabeth/lib/output/DayOneExport.js:56:11)
    at /usr/local/lib/node_modules/elizabeth/lib/Elizabeth.js:143:17
    at Request._callback (/usr/local/lib/node_modules/elizabeth/node_modules/moves-api/lib/MovesApi.js:126:13)
    at Request.self.callback (/usr/local/lib/node_modules/elizabeth/node_modules/moves-api/node_modules/request/request.js:344:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/elizabeth/node_modules/moves-api/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/elizabeth/node_modules/moves-api/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

**Comment by blueneogeo** [comment]
Just a thought, could this be the API of moves rejecting the request and giving an error which the app then cannot handle (invalid data). I wonder since sometimes even the 7 days call fails with the same error.

**Comment by thoughtgap** [comment]
I get the error from 18 days on. 17 works fine. My user profile is from 2015/02/08 (now it's 2015/02/25 in my time zone). I get the "> WHAT? Error:  the requested range must be between user profiles first date and today" error only from 19 days on - maybe a "=" is missing after a "<"?

**Comment by mrjcleaver** [comment]
Was this ever fixed?

**Comment by swcoleman** [comment]
did you ever get this to work? I am having trouble.
